# Generated by Django 4.0.1 on 2022-01-21 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_latin', models.CharField(max_length=100, unique=True)),
                ('name_cyrillic', models.CharField(max_length=100, unique=True)),
                ('file', models.FileField(upload_to='files')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.section')),
            ],
        ),
    ]
