# Generated by Django 4.0.1 on 2022-01-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='audio_true',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
