# Generated by Django 4.0.1 on 2022-01-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_audio_audio_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Youtube Video Id'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio_true',
            field=models.BooleanField(verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='Audio File'),
        ),
    ]
